### ISSUE TITLE
운영 서버 배포 과정에 테스트 서버의 데이터베이스를 동기화하는 스크립트 추가

### ISSUE THREAD

**Issue by mingmingmon** [kgu-clab/clab-platforms-server#496]
### Describe

prod 서버 배포 성공 후 prod 서버의 DB 내용을 stage 서버 DB에 적용할 수 있도록 합니다.

해당 작업은 아래와 같은 이유로 추진하게 되었습니다.

1. 테스트의 신뢰성: prod 서버 배포 후 새로운 기능을 추가적으로 개발하면서 해당 기능이 잘 동작하는지 확인하기 위해 stage 서버에서 테스트를 진행하게 됩니다. 이 때, 데이터가 prod 서버와 다르다면 실제 배포된 상황에서 발생할 수 있는 다양한 상황이 고려되지 않기에 테스트 결과를 신뢰할 수 없게 됩니다. 따라서, prod 서버 배포 후 stage 서버의 데이터도 동기화함으로써 새로운 기능의 테스트 신뢰성을 높일 수 있습니다.

2. 버그 재현: 특정 버그가 prod서버에서 발생했을 때, stage 서버 환경에서 동일한 데이터를 사용해 버그를 재현하고 디버깅하는 것이 중요합니다. prod서버과 stage 서버 데이터가 일치하지 않으면, 버그 재현이 어려워지고 문제 해결이 지연될 수 있습니다. 지금까지는 문제가 되는 테이블을 prod 서버에서 dump를 뜨고 stage서버에 옮기는 방식으로 환경을 재현하곤 했습니다. 동기화 작업은 버그 수정 전 이러한 불편한 절차를 줄일 수 있습니다.

### Tasks

- [ ] prod 서버 배포 성공 후 DB 내용을 stage 서버 DB에 적용하는 파이프라인 스크립트 작성

**Comment by limehee** [comment]
파이프라인 없이 DB 동기화시킬 수 있는 스크립트도 작성해주면 좋을 것 같아요.
